import actions from "../../state/actions";
import {
  generateCmdsFromActions,
  redux
} from "effects-as-data-redux";
import {
  cmds
} from "effects-as-data-universal/es5";
import * as reduxForm from "redux-form";
<% for(var i=0; i < cmds.length; i++) {%>
import * as <%= cmds[i] %>
from "./<%= cmds[i] %>";
<% } %>


const reduxFormActions = {};

Object.keys(reduxForm).reduce((key, actions) => {
  typeof reduxForm[key] === "function" && (reduxFormActions[key] = reduxForm[key]);
});

const autoGeneratedCmdsFromReduxActions = {
  ...generateCmdsFromActions(actions),
  ...generateCmdsFromActions(reduxFormActions)
};

// Combine the commands to access the redux state from effects-as-data-redux,
// the generated commands from the redux actions in this project and the
// effects-as-data-universal commands
export default {
  ...redux,
  ...autoGeneratedCmdsFromReduxActions,
  ...cmds, <% for(var i=0; i < cmds.length; i++) {%> ...<%= cmds[i] %>,
  <% } %>
};
